when:
  - event: [push, manual]
    branch: main

steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: openuem/openuem-cert-manager
      tags:
        - latest
        - 0.10.0
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
